version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - mongo
  