version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always
    networks:
      - loadbalancing
  memcached:
    image: sameersbn/memcached:1.5.6-2
    container_name: memcached
    ports:
      - "11211:11211"
    restart: always
    networks:
      - loadbalancing
  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
    deploy:
      replicas: 2
    networks:
      - loadbalancing
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - "3500:3500"
    networks:
      - loadbalancing
    depends_on:
      - mongo
      - app

networks:
  loadbalancing:
  